Traceback (most recent call last):
  File "C:\Users\kamac\miniconda3\envs\ml_venv\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\kamac\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\kamac\miniconda3\envs\ml_venv\lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\kamac\miniconda3\envs\ml_venv\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\kamac\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\kamac\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\kamac\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import missingno as msno
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
#from rdkit import Chem
#from rdkit.Chem import Draw
from scipy.stats import kstest, norm
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from IPython.display import display
from sklearn.pipeline import Pipeline
from matplotlib.colors import LinearSegmentedColormap
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mImportError[0m                               Traceback (most recent call last)
Cell [1;32mIn[1], line 2[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[1;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mmissingno[39;00m [38;5;28;01mas[39;00m [38;5;21;01mmsno[39;00m
[0;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mseaborn[39;00m [38;5;28;01mas[39;00m [38;5;21;01msns[39;00m
[0;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m

File [1;32m~\miniconda3\envs\ml_venv\lib\site-packages\missingno\__init__.py:1[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mmissingno[39;00m [38;5;28;01mimport[39;00m matrix
[0;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mmissingno[39;00m [38;5;28;01mimport[39;00m bar
[0;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mmissingno[39;00m [38;5;28;01mimport[39;00m heatmap

File [1;32m~\miniconda3\envs\ml_venv\lib\site-packages\missingno\missingno.py:2[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mas[39;00m [38;5;21;01mmpl[39;00m
[0;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mimport[39;00m gridspec
[0;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m

File [1;32m~\miniconda3\envs\ml_venv\lib\site-packages\matplotlib\__init__.py:263[0m
[0;32m    258[0m         [38;5;28;01mif[39;00m parse_version(module[38;5;241m.[39m__version__) [38;5;241m<[39m parse_version(minver):
[0;32m    259[0m             [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mMatplotlib requires [39m[38;5;132;01m{[39;00mmodname[38;5;132;01m}[39;00m[38;5;124m>=[39m[38;5;132;01m{[39;00mminver[38;5;132;01m}[39;00m[38;5;124m; [39m[38;5;124m"[39m
[0;32m    260[0m                               [38;5;124mf[39m[38;5;124m"[39m[38;5;124myou have [39m[38;5;132;01m{[39;00mmodule[38;5;241m.[39m__version__[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m--> 263[0m [43m_check_versions[49m[43m([49m[43m)[49m
[0;32m    266[0m [38;5;66;03m# The decorator ensures this always returns the same handler (and it is only[39;00m
[0;32m    267[0m [38;5;66;03m# attached once).[39;00m
[0;32m    268[0m [38;5;129m@functools[39m[38;5;241m.[39mcache
[0;32m    269[0m [38;5;28;01mdef[39;00m [38;5;21m_ensure_handler[39m():

File [1;32m~\miniconda3\envs\ml_venv\lib\site-packages\matplotlib\__init__.py:259[0m, in [0;36m_check_versions[1;34m()[0m
[0;32m    257[0m module [38;5;241m=[39m importlib[38;5;241m.[39mimport_module(modname)
[0;32m    258[0m [38;5;28;01mif[39;00m parse_version(module[38;5;241m.[39m__version__) [38;5;241m<[39m parse_version(minver):
[1;32m--> 259[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mMatplotlib requires [39m[38;5;132;01m{[39;00mmodname[38;5;132;01m}[39;00m[38;5;124m>=[39m[38;5;132;01m{[39;00mminver[38;5;132;01m}[39;00m[38;5;124m; [39m[38;5;124m"[39m
[0;32m    260[0m                       [38;5;124mf[39m[38;5;124m"[39m[38;5;124myou have [39m[38;5;132;01m{[39;00mmodule[38;5;241m.[39m__version__[38;5;132;01m}[39;00m[38;5;124m"[39m)

[1;31mImportError[0m: Matplotlib requires numpy>=1.23; you have 1.22.4

